apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
data:
  ME_CONFIG_MONGODB_SERVER: mongo-service
  ME_CONFIG_MONGODB_PORT: "27017"
  ME_CONFIG_BASICAUTH_USERNAME: "admin"  # Optional: Basic authentication for Mongo Express UI
  ME_CONFIG_BASICAUTH_PASSWORD: "adminpass"  # Optional: Basic authentication for Mongo Express UI
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret  # Reusing the MongoDB secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret  # Reusing the MongoDB secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo-service
        envFrom:
        - configMapRef:
            name: mongo-express-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30007
  type: NodePort
